### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by huxiaoman7** [walid-ahmad/AI_Artistry#1]
Hi,when I run the python code, it doesn't work:
`AT8864:AI_Artistry shelter$ python main.py
Using Theano backend.
Traceback (most recent call last):
  File "main.py", line 128, in <module>
    tf_session = K.get_session()
AttributeError: 'module' object has no attribute 'get_session'`

**Comment by walid0925** [comment]
Hi, you need to use TensorFlow as your keras backend. I've updated the README.md file with this note. See here for more help: https://keras.io/backend/
